markdown: kramdown

collections:
  my_categories:
    output: true
    permalink: /blog/categories/:name
  my_tags:
    output: true
    permalink: /blog/tags/:name
  my_archives:
    output: true
    permalink: /blog/archives/:path

plugins:
  - jekyll-paginate

paginate: 12
paginate_path: "/blog/page/:num/"

url: https://DAGfans.org
disqus_shortname: dagfans


